# Generated by Django 3.2 on 2026-08-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_courseunitdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('institution_type', models.CharField(choices=[('TECHNICAL_COLLEGE', 'Technical College'), ('UNIVERSITY', 'University'), ('INSTITUTE', 'Institute'), ('OTHER', 'Other')], default='TECHNICAL_COLLEGE', max_length=50)),
                ('slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(help_text='Full location and P. O. Box address')),
                ('telephone_1', models.CharField(max_length=20)),
                ('telephone_2', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('academic_units', models.CharField(blank=True, help_text='Comma-separated academic units e.g., COLLEGES, FACULTIES, DEPARTMENTS', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='attendance.institution')),
            ],
            options={
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='attendance.faculty'),
        ),
    ]
