# Generated by Django 3.2 on 2026-08-11 10:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20260809_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('revenue_share_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('fee_type', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('FUNCTIONAL', 'Functional Fee'), ('OTHER', 'Other / Sundry Fee'), ('GRADUATION', 'Graduation Fee')], default='FUNCTIONAL', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('element', models.ForeignKey(limit_choices_to={'fee_type': 'OTHER'}, on_delete=django.db.models.deletion.CASCADE, to='attendance.feeelement')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='GraduationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='E.g., 2025/2026', max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('clearance_status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEARED', 'Cleared')], default='PENDING', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_fees', to='attendance.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank if standard for all programs', null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.course')),
                ('element', models.ForeignKey(limit_choices_to={'fee_type': 'FUNCTIONAL'}, on_delete=django.db.models.deletion.CASCADE, to='attendance.feeelement')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_fees', to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='FeeWaiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiver_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount (%)'), ('FIXED', 'Fixed Amount Discount')], default='PERCENTAGE', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Discount percentage or exact amount', max_digits=10)),
                ('reason', models.TextField()),
                ('date_granted', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'ACCOUNTANT']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='attendance.studentprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructureCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('copied_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_copies', to='attendance.academicterm')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_copies', to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='FeeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='TuitionAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_amounts', to='attendance.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuition_amounts', to='attendance.academicterm')),
            ],
            options={
                'unique_together': {('course', 'term')},
            },
        ),
    ]
