# Generated by Django 3.2 on 2026-08-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_affiliate_feeapproval_feeelement_feestructurecopy_feewaiver_functionalfee_graduationfee_otherfee_tui'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionamount',
            name='fee_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuition_amounts', to='attendance.feeelement'),
        ),
        migrations.AlterUniqueTogether(
            name='tuitionamount',
            unique_together={('course', 'term', 'fee_element')},
        ),
    ]
