# Generated by Django 3.2 on 2026-08-18 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_credit_units', models.PositiveIntegerField(default=120)),
                ('duration_years', models.PositiveIntegerField(default=3)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('grading_system', models.CharField(default='GPA 5.0', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='attendance.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_cycle', models.CharField(help_text='e.g., 5-Year Periodic Review 2026', max_length=50)),
                ('review_board', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='SCHEDULED', max_length=20)),
                ('findings_and_recommendations', models.TextField(blank=True, null=True)),
                ('next_review_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='attendance.course')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumDevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developments', to='attendance.course')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_curricula', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_stage', models.CharField(help_text='e.g., Department Board, Faculty Board, Senate', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUESTED', 'Revision Requested')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateTimeField(auto_now=True)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='attendance.curriculumdevelopment')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curriculum_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CBEFormSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_code', models.CharField(max_length=50)),
                ('competency_description', models.TextField()),
                ('performance_criteria', models.TextField()),
                ('assessment_method', models.CharField(choices=[('PRACTICAL', 'Practical Demonstration'), ('PORTFOLIO', 'Portfolio Assessment'), ('WRITTEN', 'Written Examination'), ('PROJECT', 'Project Work')], default='PRACTICAL', max_length=30)),
                ('weightage_percent', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('passing_threshold', models.DecimalField(decimal_places=2, default=60.0, max_digits=5)),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbe_settings', to='attendance.courseunit')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year_level', models.PositiveIntegerField(default=1, help_text='e.g. Year 1, 2, 3')),
                ('semester', models.PositiveIntegerField(default=1, help_text='e.g. Semester 1, 2')),
                ('is_core', models.BooleanField(default=True, help_text='Core vs Elective unit')),
                ('credit_units', models.PositiveIntegerField(default=3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_structures', to='attendance.course')),
                ('course_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_positions', to='attendance.courseunit')),
            ],
            options={
                'unique_together': {('course', 'academic_year_level', 'semester', 'course_unit')},
            },
        ),
    ]
