# Generated by Django 3.2 on 2026-08-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_cbeformsetting_curriculumapproval_curriculumdevelopment_curriculumreview_curriculumstructure_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='credit_units',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
