# Generated by Django 3.2 on 2026-08-19 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_courseunit_credit_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='academic_status',
            field=models.CharField(blank=True, default='ACTIVE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='billing_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='intake',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsorship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='StudentApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('BIO_DATA', 'Student Bio-Data Change'), ('ACADEMIC', 'Student Academic Details Change'), ('ACCOUNT_STATUS', 'Account Status Change'), ('UPLOAD', 'Uploaded Student Approval')], max_length=30)),
                ('payload_data', models.JSONField(help_text='Contains proposed data updates or bulk upload JSON')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(choices=[('CAMPUS', 'Campus Resident'), ('NON_RESIDENT', 'Non-Resident')], default='CAMPUS', max_length=20)),
                ('payment_status', models.CharField(choices=[('PAID', 'Paid Students'), ('PENDING', 'Pending Payment')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.academicterm')),
                ('hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.hostel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residence_applications', to='attendance.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'academic_term')},
            },
        ),
    ]
