# Generated by Django 3.2 on 2026-08-27 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_campus_metadatacategory_metadatavalue'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='metadatavalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metadatavalue',
            name='category',
        ),
        migrations.DeleteModel(
            name='MetadataCategory',
        ),
        migrations.DeleteModel(
            name='MetadataValue',
        ),
    ]
