# Generated by Django 3.2 on 2026-08-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_auto_20260827_0918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={},
        ),
        migrations.AlterField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='attendance.institution'),
        ),
        migrations.AlterUniqueTogether(
            name='campus',
            unique_together=set(),
        ),
    ]
