# Generated by Django 3.2 on 2026-09-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20260902_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('Semester 1', 'Semester 1'), ('Semester 2', 'Semester 2'), ('Semester 3', 'Semester 3'), ('Semester 4', 'Semester 4')], help_text='e.g., Semester 1, Semester 2, Semester 3, Semester 4', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], help_text='e.g., Term 1, Term 2, Term 3', max_length=50, unique=True),
        ),
    ]
