# Generated by Django 3.2 on 2026-09-09 06:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_auto_20260902_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='courseunit',
            name='contact_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='department',
            field=models.ForeignKey(blank=True, help_text="The owning department. Maps to 'DEPARTMENT CODE' / 'PARENT DEPARTMENT'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_course_units', to='attendance.department'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='field_work_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='is_core',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='lecture_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='practical_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='semester',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='serviced_departments',
            field=models.ManyToManyField(blank=True, help_text="Other departments this unit is taught to. Maps to 'SERVICED DEPARTMENTS' (comma-separated codes).", related_name='serviced_course_units', to='attendance.Department'),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text="Maps to 'DEPARTMENT CODE', e.g. DME, DCE, DEE, DCR, ICT.", max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.campus'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='district_of_origin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_condition',
            field=models.CharField(blank=True, help_text="e.g. 'EARLY ENROLLMENT' / 'LATE ENROLLMENT'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_token',
            field=models.CharField(blank=True, help_text="e.g. 'ENR1712688936'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='entry_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_students', to='attendance.academicyear'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.hostel'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_enrolled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Ugandan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIN / National ID'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='other_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='programme_type',
            field=models.CharField(blank=True, choices=[('DAY', 'Day'), ('WEEKEND', 'Weekend'), ('EVENING', 'Evening')], help_text="Maps to 'PROGRAMME TYPE' column, e.g. DAY / WEEKEND.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='provisional_registration_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='registration_condition',
            field=models.CharField(blank=True, help_text="e.g. 'EARLY REGISTRATION' / 'LATE REGISTRATION'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='registration_status',
            field=models.CharField(blank=True, help_text="e.g. 'REGISTERED' / 'NOT REGISTERED'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='registration_type',
            field=models.CharField(blank=True, help_text="e.g. 'FULL REGISTRATION' / 'PROVISIONAL REGISTRATION'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='residence_status',
            field=models.CharField(blank=True, help_text='e.g. Resident / Non-Resident', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsorship_scheme',
            field=models.CharField(blank=True, help_text="e.g. 'GOVERNMENT SPONSORSHIP'. NOTE: in the HEMIS export this value is exported under the mislabelled 'DISTRICT' column, not the student's real district.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='sponsorship_type',
            field=models.CharField(blank=True, choices=[('GOVERNMENT', 'Government'), ('PRIVATE', 'Private')], help_text="From the HEMIS export. NOTE: in the 'ENROLLMENT AND REGISTRATION REPORT' template this value is exported under the mislabelled 'DATE OF BIRTH' column.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='uace_index_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='uce_index_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='functional_fees_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='functional_fees_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='functional_fees_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='other_fees_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='other_fees_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='other_fees_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='tuition_amount_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='tuition_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='studenttermfee',
            name='tuition_invoice_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Maps to the 'Verified' Yes/No column in the Group Users export."),
        ),
        migrations.AddField(
            model_name='user',
            name='other_names',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, choices=[('MR.', 'Mr.'), ('MRS.', 'Mrs.'), ('MISS', 'Miss'), ('DR.', 'Dr.'), ('ENG.', 'Eng.'), ('PROF.', 'Prof.')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='term',
            field=models.CharField(choices=[('TERM_1', 'Term 1'), ('TERM_2', 'Term 2'), ('TERM_3', 'Term 3'), ('RECESS', 'Recess Term'), ('SEMESTER_1', 'Semester 1'), ('SEMESTER_2', 'Semester 2')], max_length=10),
        ),
        migrations.AlterField(
            model_name='courseunit',
            name='name',
            field=models.CharField(help_text="Maps to 'COURSE TITLE'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Maps to 'PARENT DEPARTMENT' in the COURSE-UNIT-REPORT.", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='sponsorship',
            field=models.CharField(blank=True, help_text='Legacy free-text sponsorship note (manual entry).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.stream'),
        ),
        migrations.AlterField(
            model_name='studenttermfee',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Maps to 'TOTAL AMOUNT PAID'.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='studenttermfee',
            name='total_fees_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Maps to 'TOTAL AMOUNT INVOICED'.", max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher/Lecturer'), ('STUDENT', 'Student'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTANT', 'Accountant'), ('REGISTRAR', 'Academic Registrar'), ('DEAN', 'Dean of Students'), ('HOD', 'Head of Department'), ('PARENT', 'Parent'), ('SYSTEM_SUPPORT', 'System Support'), ('SYSTEM_ADMIN', 'System Administrator'), ('FINANCE', 'Finance'), ('POINT_OF_SERVICE', 'Point of Service'), ('ASSISTANT_REGISTRAR', 'Assistant Academic Registrar'), ('PRINCIPAL', 'Principal')], default='STUDENT', help_text="Primary/default role, used by existing limit_choices_to checks elsewhere in this file. A staff member with several roles (e.g. 'System Administrator; Academic Registrar; Finance; Lecturer; HOD') has every one of them recorded in StaffRole below — this field alone cannot hold more than one.", max_length=25),
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TEACHER', 'Teacher/Lecturer'), ('STUDENT', 'Student'), ('WARDEN', 'Warden'), ('LIBRARIAN', 'Librarian'), ('ACCOUNTANT', 'Accountant'), ('REGISTRAR', 'Academic Registrar'), ('DEAN', 'Dean of Students'), ('HOD', 'Head of Department'), ('PARENT', 'Parent'), ('SYSTEM_SUPPORT', 'System Support'), ('SYSTEM_ADMIN', 'System Administrator'), ('FINANCE', 'Finance'), ('POINT_OF_SERVICE', 'Point of Service'), ('ASSISTANT_REGISTRAR', 'Assistant Academic Registrar'), ('PRINCIPAL', 'Principal')], max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
