# Generated by Django 3.2 on 2026-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_auto_20260909_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='award',
            field=models.CharField(blank=True, help_text="Maps to 'award' - the qualification awarded on completion. Mirrors study_level in the exports seen so far, but modelled separately since the source treats them as distinct fields.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='award_label',
            field=models.CharField(blank=True, help_text="Maps to 'award_label'. Always blank in the ALL_Programmes export seen so far, kept for forward compatibility.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='create_approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text="Maps to 'create_approval_status' - approval state of this programme record in the source system.", max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_measure',
            field=models.CharField(blank=True, default='YEAR', help_text="Maps to 'duration_measure', e.g. YEAR. The unit that ProgrammeSetting.duration_years is counted in.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_measure_label',
            field=models.CharField(blank=True, help_text="Maps to 'duration_measure_label'. Always blank in the ALL_Programmes export seen so far, kept for forward compatibility.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_measure_source_id',
            field=models.CharField(blank=True, help_text="Maps to 'duration_measure_id' - the source system's internal lookup id for duration_measure.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_modular',
            field=models.BooleanField(default=False, help_text="Maps to 'is_modular' - whether the programme can be taken/enrolled module-by-module rather than as a full programme."),
        ),
        migrations.AddField(
            model_name='course',
            name='study_level',
            field=models.CharField(blank=True, choices=[('CERTIFICATE', 'Certificate'), ('DIPLOMA', 'Diploma'), ('HIGHER DIPLOMA', 'Higher Diploma'), ('DEGREE', 'Degree')], help_text="Maps to 'study_level', e.g. DIPLOMA, HIGHER DIPLOMA, CERTIFICATE.", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='study_level_label',
            field=models.CharField(blank=True, help_text="Maps to 'study_level_label'. Always blank in the ALL_Programmes export seen so far, kept for forward compatibility.", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='study_level_source_id',
            field=models.CharField(blank=True, help_text="Maps to 'programme_study_level_id' - the source system's internal lookup id for study_level.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='version_title',
            field=models.CharField(blank=True, help_text="Maps to 'version_title' - curriculum version label from the source system, when set.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='source_department_id',
            field=models.CharField(blank=True, help_text="Maps to 'department_id' in the ALL_Programmes export (the source system's internal id for this department).", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text="Maps to 'programme_code'.", max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text="Maps to 'programme_title'.", max_length=255),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text="Maps to 'DEPARTMENT CODE', e.g. DME, DCE, DEE, DCR, ICT. / 'department_code' in the ALL_Programmes export.", max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Maps to 'PARENT DEPARTMENT' in the COURSE-UNIT-REPORT / 'department_title' in the ALL_Programmes export.", max_length=255, unique=True),
        ),
    ]
